### ISSUE TITLE
add these features

### ISSUE THREAD

**Issue by creator1134** [alex2112/animefreak-downloader#2]
pls can you add these features to the script :
1. while batch downloading script select the server itself,  add the option similar to single file download where script asks while server to choose for downloading like
   1. mp4uploads
   2. animefreak.tv
   3. videoweed 

like this so we can select a server by our choice.
1. There is a issue that if i start batch downloading a whole series after few minutes the downloading speed decreases exponentially. My speed is 2 Mbps, if i ran script for more than 30 min its DL speed decrease to 20kbps to 50 Kbps , and i have to restart the script again.
2. Can you provide the option to save the download link in a text file so i can fed the data to XDM ,IDM FDM directly. ( just have to save all the links available in a text file for the animefreak.tv own server RAW ips /anime1.com links )

Thx

**Comment by alex2112** [comment]
For the first it would make sense to set the preferred servers beforehand in an option from most significant to least significant because the whole point of batch mode is to run uninterruptible. Will see either that or an option similar as you suggested.
About the speed issue, maybe the server throttles the speed after an amount of time? I haven't notice something like this maybe because i don't do batch downloads that much.
Someone else suggested aria2 for accelerated downloads instead of wget, so i can implement that if it makes any difference for your speed issues. It supports multiple connections and resuming from partially downloaded files. It should be in your distros repos.

**Comment by alex2112** [comment]
I've added an option for the order the servers appear during selection and in batch mode.
Also added aria2 as alternative. Experiment with MAX_CONNECTIONS option and see if that resolves your speed issues.
